const fs = require('fs');
const path = require('path');

const publicDir = path.join(__dirname, 'public');
const outputFile = path.join(__dirname, 'src/app/tracks.ts');

try {
  const files = fs.readdirSync(publicDir);
  const tracks = files
    .filter(file => file.toLowerCase().endsWith('.mp3'))
    .map(file => `/${file}`);

  const content = `// Auto-generated by generate-tracks.js\nexport const TRACKS: string[] = ${JSON.stringify(tracks, null, 2)};\n`;
  
  fs.writeFileSync(outputFile, content);
  console.log(`Successfully generated src/app/tracks.ts with ${tracks.length} tracks.`);
} catch (error) {
  console.error('Error generating tracks:', error);
}
